### ISSUE TITLE
代码高亮显示

### ISSUE THREAD

**Issue by billie66** [happypeter/patch-typist#1]

**Comment by happypeter** [comment]
稍微模仿一下 vscode 的界面，不用导航栏。

**Comment by happypeter** [comment]
参考 https://github.com/CompuIves/codesandbox-client

**Comment by billie66** [comment]
直接使用 highlight.js 让代码高亮，不能使用 react-typist 实现打印效果，自己实现代码高亮，不影响打印效果

**Comment by billie66** [comment]
调用 prism.js 的接口可以实现代码高亮
