### ISSUE TITLE
后台系统

### ISSUE THREAD

**Issue by happypeter** [happypeter/patch-typist#2]
- 录到视频中的是前台系统
  - 显示一个文件名
  - 代码内容
- 我自己操作用的是后台系统
  - 选择要显示哪个文件，都是当前 commit 的文件，但是可能会选择没有修改的文件
  -  选择前端要开始运行哪个  patch ，一个文件中的多个 patch 不一定一次讲完

**Comment by happypeter** [comment]
后台系统不能跟前台放到一个页面中，所以可能需要做成一个独立应用，那么前后台就只能通过 API 通信了，这样前台提供可能需要通过 socket 拿到后台的指令和数据。

**Comment by happypeter** [comment]
可以先挑战这样一个效果：

- 后台弄一个 form ，form 里面我粘贴一个 patch
- 前台能自动把这个 patch 打出来

这个是最简任务了，这个如果都实现不了，证明我的思路是不可行的。

**Comment by billie66** [comment]
通过 socket.io 可以完成上述最简单的任务，思路可行

**Comment by billie66** [comment]
现在前后台以及 server 三端可以借助 socket.io 进行通信，不需要 axios 请求 server 端数据了

**Comment by billie66** [comment]
1. 后台已经完成的功能如下：

* 通过 form 表单输入将要操作的 git 仓库地址
* 列出该 git 仓库的所有 commit
* 选择一个 commit，列出当前版本中的所有文件，并把修改文件名高亮显示
* 选择修改文件，显示 patch 信息

2. 前台完成的功能如下：

*  展示后台选中的文件名
*  展示文件内容且高亮显示
* 按行打印文件 patch，一行打印完毕之后，高亮显示

3. 需要完善的功能是：

* 后台 patch 信息高亮显示
* 前台不能支持 jsx 语法高亮
* 对于删除行，前台打印比较野蛮，先删除整行，然后打印修改的整行内容，最好能精准到只打印修改内容
* 后台只要选中文件，前台都会列出来，没有区分版本

**Comment by billie66** [comment]
把任务分解一下，单独开 issue 吧

**Comment by billie66** [comment]
3. 已经完善的功能：

* 后台 patch 信息高亮显示
* 前台支持 jsx, javascript, markup, json 等语法高亮
* 后台切换版本，选中文件，前后会清空上一个版本的文件，然后显示新版本文件

**Comment by happypeter** [comment]
对，单独开比较好

**Comment by billie66** [comment]
好的
