### ISSUE TITLE
平滑移动到下一个 hunk

### ISSUE THREAD

**Issue by billie66** [happypeter/patch-typist#22]
打印完一个 hunk ，平滑移动到下一个 hunk 的起始位置。

**Comment by billie66** [comment]
https://github.com/fisshy/react-scroll

**Comment by happypeter** [comment]
这个问题的陈述本身就不太准确，因为同一个 hunk ，如果比较大，也可能打印的时候溢出 viewport 范围。所以不用考虑 hunk 。而是要以当前打印行为基准。

- 如果当前行已经是 ViewPort 底部倒数第二行了，就直接网上滚动到距离 viewport 顶部第二行(这样，每次要滚动多少行，基本上可以算出来了）
- 然后继续打印，一直到当前行又变成倒数第二行了，再次执行滚动。

**Comment by happypeter** [comment]
由于咱们的字体大小是不变的，所以咱们的 Editor 视窗就保持是行高的一个整数倍，每次滚动的结果也是刚好显示出所有行的完整内容，不会像真实的编辑器那样显示出一行的上半部分。

**Comment by happypeter** [comment]
下面的 patch 解决的问题是：

- 设置滚动耗时为3秒（不管滚动多少行）
- 滚动完毕，再等待三秒，才开始打印下一行内容（ applyMutation ）

**Comment by happypeter** [comment]
SCROLL_TO_TOP 这个操作应该被替换掉，切换文件的时候，应该执行一个重置操作

**Comment by happypeter** [comment]
现在要调整的是 utils.scrollToY

**Comment by happypeter** [comment]
修改了获取 toY 数值的算法，现在垂直方向的滚动的距离已经合适，不会遮挡打印的代码

**Comment by happypeter** [comment]
上面的写法还是有问题，看来问题还是比较复杂的，所以先做适度简化，然后逐步完善。

**Comment by happypeter** [comment]
- 现在先控制编辑器视窗总高度，20x20 
  - 意思是，视窗只显示20行，每行的行高是20px

**Comment by happypeter** [comment]
先来实现这一步。

**Comment by happypeter** [comment]
getScroolDownLines 的测试用例如下：

```
/*

let result = getToY(18, {offset = 0}) 
result === 0 ，当前行是第18行，不会触发滚动

let result = getToY(19, {offset = 0}) 
当前行是第十九行，触发滚动
result === 17 * 20 ，也就是要滚动17行

let result = getToY(21, {offset = 0}) 
result === 19 * 20 ，也就是要滚动19行

let result = getToY(24, {offset = 3}) 
result === 19 * 20 ，也就是要滚动19行，24-3-2
*/
```

**Comment by happypeter** [comment]
现在的问题是 scrollMore 不工作了，来修复一下。

**Comment by happypeter** [comment]
现在功能基本工作了。每次滚动后都会在第二行开始打印。

问题是，如果当前文件已经滚动到底了，但是同时滚动的距离又跟 toY 的实际数量不相等，就会造成打印过程中，当前行到了倒数第二行，也不会触发 scroll 。

**Comment by happypeter** [comment]
上面问题修复了。现在滚动工作正常。
